[?1034h
Warning: cqlshrc config files were found at both the old location (/root/.cqlshrc) and                 the new location (/root/.cassandra/cqlshrc), the old config file will not be migrated to the new                 location, and the new location will be used for now.  You should manually                 consolidate the config files at the new location and remove the old file.
Connection error: ('Unable to connect to any servers', {'172.17.0.3': AuthenticationFailed('Remote end requires authentication.',)})
